site_name: Méthodes des sciences sociales
site_url: https://example.com/

theme:
  font:
    text: Input
    code: Input Mono
  langage: fr
  name: material
  logo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Glider.svg"
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: amber
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mickaeltemporao
extra_css:
  - stylesheets/extra.css
# repo_url: https://github.com/mkdocs/mkdocs/

# Page tree
nav:
  - syllabus.md
  - Horaires: schedule.md
  - Modules:
    - Semestre 1:
      - modules/syllabus.md
      - modules/science.md
      - modules/causality.md
      - modules/sampling.md
      - modules/measurement.md
      - modules/replication.md
    - Semestre 2:
      - modules/programming.md
      - modules/statistics.md
      - modules/variables.md
      - modules/hypothesis.md
      - modules/analysis.md
      - modules/communication.md
  - Activités:
    - activities/participation.md
    - activities/assignments-winter.md
    - activities/report-winter.md
  - Resources:
    - resources/book.md
    - resources/writing.md
    - resources/coding.md
  - Chat: "https://sciencespobordeaux.slack.com/messages/méthodes-des-sciences-sociales/"

