site_name: Méthodes des sciences sociales
site_url: https://example.com/

theme:
  font:
    text: Input
    code: Input Mono
  langage: fr
  name: material
  icon:
    logo: fontawesome/solid/book
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: amber
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: Copyright &copy; 2020 - 2021 Mickael Temporão,  <a href="https://spdx.org/licenses/AGPL-3.0-or-later.html">GNU Affero General Public License v3.0</a>.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mickaeltemporao
extra_css:
  - stylesheets/extra.css
# repo_url: https://github.com/mkdocs/mkdocs/

# Page tree
nav:
  - syllabus.md
  - Horaires: schedule.md
  - Modules:
    - Semestre 1:
      - modules/syllabus.md
      - modules/science.md
      - modules/causality.md
      - modules/sampling.md
      - modules/measurement.md
      - modules/replication.md
    - Semestre 2:
      - modules/programming.md
      - modules/statistics.md
      - modules/variables.md
      - modules/hypothesis.md
      - modules/analysis.md
      - modules/communication.md
  - Activités:
    - activities/participation.md
    - activities/assignments-winter.md
    - activities/report-winter.md
    # - Semestre 2:
    #   - activities/assignments-summer.md
  - Resources:
    - Materials: resources.md
    - Template: template_research_design.md
    - Participation: participation.md
    - Travaux Pratiques: participation.md
    - Rapports de Recherche: participation.md
  - Chat: "https://sciencespobordeaux.slack.com/messages/méthodes-des-sciences-sociales/"
