site_name: Méthodes des sciences sociales
site_url: https://example.com/
nav:
    - <i class="fa fa-home fa-lg"></i> About: index.md
    - <i class="fa fa-home fa-lg"></i> Calendar: index.md
    - <i class="fa fa-home fa-lg"></i> Resources: index.md
    - <i class="fa fa-home fa-lg"></i> Activités:
        - 'Participation': 'writing-your-docs.md'
        - 'Travaux Pratiques': 'styling-your-docs.md'
        - 'Rapports de Recherche': 'styling-your-docs.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
theme:
    name: flatly
    locale: en
    highlightjs: true
    hljs_style: github
    hljs_languages:
        - yaml
        - python
    shortcuts:
        next: 78     # n
        previous: 80 # p
        search: 191  # /
markdown_extensions:
    - fontawesome_markdown

copyright: Copyright &copy; 2021 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

repo_url: https://github.com/mkdocs/mkdocs/

