site_name: Méthodes des sciences sociales
site_url: https://example.com/

theme:
  font:
    text: Input
    code: Input Mono
  langage: fr
  name: material
  icon:
    logo: fontawesome/brands/facebook
  favicon: images/favicon.ico
  palette:
    scheme: slate
    primary: amber
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: Copyright &copy; 2020 - 2021 Mickael Temporão,  <a href="https://spdx.org/licenses/AGPL-3.0-or-later.html">GNU Affero General Public License v3.0</a>.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mickaeltemprao

# repo_url: https://github.com/mkdocs/mkdocs/

# Page tree
nav:
  - syllabus.md
  - Cours:
    - units/index.md
    - Cours 1: units/syllabus.md
    - Cours 2: units/science.md
    - Cours 3: units/science.md
    - Cours 4: units/causality.md
    - Cours 5: units/causality.md
    - Cours 6: units/sampling.md
    - Cours 7: units/sampling.md
    - Cours 8: units/measurement.md
    - Cours 9: units/measurement.md
    - Cours 10: units/replication.md
    - Cours 11: units/replication.md
    - Cours 12: units/retrospective.md
    - Cours 1: units/programming.md
    - Cours 2: units/programming.md
    - Cours 3: units/statistics.md
    - Cours 4: units/statistics.md
    - Cours 5: units/variables.md
    - Cours 6: units/variables.md
    - Cours 7: units/hypothesis.md
    - Cours 8: units/hypothesis.md
    - Cours 9: units/analysis.md
    - Cours 10: units/analysis.md
    - Cours 11: units/communication.md
    - Cours 12: units/communication.md
  - Misc:
    - Activités: activities.md
    - Participation: participation.md
    - Travaux Pratiques: styling-your-docs.md
    - Rapports de Recherche: styling-your-docs.md
  - Resources:
    - Materials: resources.md
    - Template: template_research_design.md
  - Insiders:
    - Sponsorship: insiders/index.md
    - Getting started:
      - Installation: insiders/getting-started.md
      - Changelog: insiders/changelog.md
  - Setup:
    - Changing the colors: setup/changing-the-colors.md
    - Changing the fonts: setup/changing-the-fonts.md
    - Changing the language: setup/changing-the-language.md
    - Changing the logo and icons: setup/changing-the-logo-and-icons.md
    - Setting up navigation: setup/setting-up-navigation.md
    - Setting up site search: setup/setting-up-site-search.md
    - Setting up site analytics: setup/setting-up-site-analytics.md
