site_name: Méthodes des sciences sociales
site_url: https://example.com/

theme:
  font:
    text: Input
    code: Input Mono
  langage: fr
  name: material
  icon:
    logo: fontawesome/solid/book
  favicon: images/favicon.ico
  palette:
    scheme: default
    primary: amber
    accent: red
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


copyright: Copyright &copy; 2020 - 2021 Mickael Temporão,  <a href="https://spdx.org/licenses/AGPL-3.0-or-later.html">GNU Affero General Public License v3.0</a>.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mickaeltemporao
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mickaeltemporao
extra_css:
  - stylesheets/extra.css
# repo_url: https://github.com/mkdocs/mkdocs/

# Page tree
nav:
  - syllabus.md
  - Horaires: units/index.md
  - Modules:
    - Module 1: units/syllabus.md
    - Module 2: units/science.md
    - Module 3: units/science.md
    - Module 4: units/causality.md
    - Module 5: units/causality.md
    - Module 6: units/sampling.md
    - Module 7: units/sampling.md
    - Module 8: units/measurement.md
    - Module 9: units/measurement.md
    - Module 10: units/replication.md
    - Module 11: units/replication.md
    - Module 12: units/retrospective.md
    - Module 1: units/programming.md
    - Module 2: units/programming.md
    - Module 3: units/statistics.md
    - Module 4: units/statistics.md
    - Module 5: units/variables.md
    - Module 6: units/variables.md
    - Module 7: units/hypothesis.md
    - Module 8: units/hypothesis.md
    - Module 9: units/analysis.md
    - Module 10: units/analysis.md
    - Module 11: units/communication.md
    - Module 12: units/communication.md
  - Resources:
    - Materials: resources.md
    - Template: template_research_design.md
    - Activités: activities.md
    - Participation: participation.md
    - Travaux Pratiques: participation.md
    - Rapports de Recherche: participation.md
  - Chat: "https://sciencespobordeaux.slack.com/messages/méthodes-des-sciences-sociales/"
